cargo_features = ["let-chains"]

[package]
name = "tinylisp_rs"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = true

[target.'cfg(not(target_env = "msvc"))'.dependencies]
 tikv-jemallocator = "0.6"

[dependencies]
itertools = "0.14.0"
nohash-hasher = "0.2.0"
refpool = "0.4.3"
thiserror = "2.0.11"
